server:
  port: 8082

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    password: admin
    hikari:
      schema: cloudtechies
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          validation:
            mode: none
txn:
  validator:
    persister:
      kafkaClusterURL: localhost:9092
      kafkaConsumerGroupName: txnValidatorPersister
      kafkaTxnDataInputTopic: txn-data-input
      restRetryCount: 5
      restBackoffTime: 100
      maxPollSize: 3
      kafkaRjctTxnDataOutputTopic: rjct-txn-data-output
      kafkaPrEnrValidTxnDataOutputTopic: prenrvalid-txn-data-output


